#!/usr/bin/env bash
# =============================================================================
# /usr/local/bin/acidwurx-setup-routing.sh
# Interface-agnostic policy-routing manager (archive: interface-agnostic law).
# * Auto-detects WAN (excludes warp/Cloudflare/wgcf/tailscale/ts interfaces)
# * Auto-detects WARP interface from patterns: CloudflareWARP warp0 wgcf cfw0
# * Writes /etc/nftables/acidwurx-interfaces.nft (consumed by containment set)
# * Installs bypass rules (prio 50-52) and LAN breakout (prio 100)
# * NO-BLACKHOLE guarantee: table 100 always has a WAN fallback default
#   (WARP down => LAN egress falls back to ISP, never a hole).
# Runs from: systemd nexo-routing.service (boot) + NetworkManager dispatcher.
# =============================================================================
set -euo pipefail

TABLE=100
LAN="192.168.1.0/24"
MESH="100.64.0.0/10"
PRIV12="172.16.0.0/12"

log() { echo "[nexo-routing] $*"; }

# --- 1. Detect interfaces -----------------------------------------------------
WAN_IF="$(ip -4 route show default 2>/dev/null | grep -vE "warp|Cloudflare|wgcf|tailscale|ts0|wt0" | awk '{print $5}' | head -n1 || true)"
WAN_GW="$(ip -4 route show default dev "${WAN_IF:-none}" 2>/dev/null | awk '{print $3}' | head -n1 || true)"
WARP_IF=""
for pat in CloudflareWARP warp0 wgcf cfw0; do
  if ip link show "$pat" >/dev/null 2>&1; then WARP_IF="$pat"; break; fi
done
log "WAN_IF=${WAN_IF:-none} WAN_GW=${WAN_GW:-none} WARP_IF=${WARP_IF:-none}"

# --- 2. Emit nftables interface definitions (atomic write) --------------------
mkdir -p /etc/nftables
TMP_NFT="$(mktemp)"
{
  echo "# Auto-generated by acidwurx-setup-routing.sh — do not edit by hand"
  if [ -n "$WAN_IF" ]; then
    echo "define wan_ifaces = { \"$WAN_IF\" }"
  else
    echo "define wan_ifaces = { \"eth0\" }"
  fi
  if [ -n "$WARP_IF" ]; then
    echo "define warp_ifaces = { \"$WARP_IF\" }"
    echo "define mesh_ifaces = { \"$WARP_IF\" }"
  else
    echo "define warp_ifaces = { \"wgcf\", \"CloudflareWARP\", \"warp0\", \"cfw0\" }"
    echo "define mesh_ifaces = { \"wgcf\", \"CloudflareWARP\", \"warp0\", \"cfw0\" }"
  fi
} > "$TMP_NFT"
mv -f "$TMP_NFT" /etc/nftables/acidwurx-interfaces.nft

# --- 3. Bypass rules (MUST outrank breakout) ----------------------------------
ip rule del to "$MESH" lookup main priority 50 2>/dev/null || true
ip rule del to "$LAN" lookup main priority 51 2>/dev/null || true
ip rule del to "$PRIV12" lookup main priority 52 2>/dev/null || true
ip rule add to "$MESH" lookup main priority 50
ip rule add to "$LAN" lookup main priority 51
ip rule add to "$PRIV12" lookup main priority 52

# --- 4. Breakout table with no-blackhole fallback -----------------------------
ip route flush table $TABLE 2>/dev/null || true
ip rule del from "$LAN" lookup $TABLE priority 100 2>/dev/null || true
if [ -n "$WARP_IF" ] && ip link show "$WARP_IF" 2>/dev/null | grep -q "state UP"; then
  ip route add default dev "$WARP_IF" table $TABLE
  if [ -n "$WAN_GW" ] && [ -n "$WAN_IF" ]; then
    ip route add default via "$WAN_GW" dev "$WAN_IF" table $TABLE metric 100 2>/dev/null || true
  fi
  log "breakout: WARP ($WARP_IF) primary, WAN fallback metric 100"
elif [ -n "$WAN_GW" ] && [ -n "$WAN_IF" ]; then
  ip route add default via "$WAN_GW" dev "$WAN_IF" table $TABLE
  log "breakout: WARP down — WAN default installed in table $TABLE (no blackhole)"
else
  log "WARNING: no WARP and no WAN default detected; table $TABLE left empty (main table still routes)"
fi
ip rule add from "$LAN" lookup $TABLE priority 100

# --- 5. NAT + forward (LAN-sourced only) --------------------------------------
if [ -n "$WARP_IF" ]; then
  iptables -t nat -C POSTROUTING -s "$LAN" -o "$WARP_IF" -j MASQUERADE 2>/dev/null || \
    iptables -t nat -A POSTROUTING -s "$LAN" -o "$WARP_IF" -j MASQUERADE
fi
if [ -n "$WAN_IF" ]; then
  iptables -t nat -C POSTROUTING -s "$LAN" -o "$WAN_IF" -j MASQUERADE 2>/dev/null || \
    iptables -t nat -A POSTROUTING -s "$LAN" -o "$WAN_IF" -j MASQUERADE
fi
iptables -P FORWARD ACCEPT 2>/dev/null || true

ip route flush cache
log "policy routing applied (bypass 50-52, breakout 100; table $TABLE)"
